### ISSUE TITLE
Helper scripts are missing (docker-build_p2p)

### ISSUE THREAD

**Issue by THS-on** [Kennox/rscc#134]
Fresh install of a Lernstick in a VM. I installed v0.6.2 as deb.
It seems that the `docker-build_p2p` folder was not created.
I started rscc with `java -jar /usr/bin/rsccfx.jar
```
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.RsccApp start
INFORMATION: Low Resolution, Text Size: 9.0
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: ssh.rc
 Exception Message: /home/user/.rscc/docker-build_p2p/ssh.rc (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: start_x11vnc.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/start_x11vnc.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: use.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/use.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: start_vncserver.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/start_vncserver.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: get.key
 Exception Message: /home/user/.rscc/docker-build_p2p/keys/get.key (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: delete.key
 Exception Message: /home/user/.rscc/docker-build_p2p/keys/delete.key (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: create.key
 Exception Message: /home/user/.rscc/docker-build_p2p/keys/create.key (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: vnc.rc
 Exception Message: /home/user/.rscc/docker-build_p2p/vnc.rc (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: start_vncviewer.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/start_vncviewer.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: port_connect.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/port_connect.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: port_share.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/port_share.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc extractJarContents
SCHWERWIEGEND: Exception thrown when reading from file: port_stop.sh
 Exception Message: /home/user/.rscc/docker-build_p2p/port_stop.sh (Datei oder Verzeichnis nicht gefunden)
Mai 18, 2017 12:41:41 PM ch.imedias.rsccfx.model.Rscc readServerConfig
SCHWERWIEGEND: Exception thrown when reading from file: /home/user/.rscc/docker-build_p2p/ssh.rc
 Exception Message: /home/user/.rscc/docker-build_p2p/ssh.rc
Mai 18, 2017 12:41:42 PM java.util.prefs.FileSystemPreferences$1 run
INFORMATION: Created user preferences directory.
Mai 18, 2017 12:41:42 PM ch.imedias.rsccfx.model.xml.SupporterHelper getDefaultSupporters
INFORMATION: Loading default supporter list
Mai 18, 2017 12:41:47 PM ch.imedias.rsccfx.model.SystemCommander executeTerminalCommand
SCHWERWIEGEND: Exception thrown when running the command: /home/user/.rscc/docker-build_p2p/use.sh 86.119.39.89 800
 Exception Message: Cannot run program "/home/user/.rscc/docker-build_p2p/use.sh": error=2, Datei oder Verzeichnis nicht gefunden
Exception in thread "Thread-7" java.lang.IllegalArgumentException
	at ch.imedias.rsccfx.model.SystemCommander.executeTerminalCommand(SystemCommander.java:51)
	at ch.imedias.rsccfx.model.Rscc.keyServerSetup(Rscc.java:202)
	at ch.imedias.rsccfx.model.Rscc.requestKeyFromServer(Rscc.java:237)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martinfrancois** [comment]
Thanks for reporting, we are aware of this issue and will take care of it. As a quick fix, you could copy the "docker-build_p2p" folder in "resources" from the master branch into "/home/user/.rscc/docker-build_p2p"

**Comment by martinfrancois** [comment]
Tested the implementation of the fix for this issue on a clean install of the lernstick. It should now work without any issues with the v0.6.3 release.
